### ISSUE TITLE
sonar-project.properties file

### ISSUE THREAD

**Issue by FahdW** [newtmitch/docker-sonar-scanner#19] opened 2018-12-17 17:33 UTC
I mounted my source code correctly and the scan is picking up some of the exclusions etc. However when it looks up the sonar.projectKey in said file it ignores it completely and just generates its own project name by default. Is it simply not adhering to these sonar-project.properties?

**Comment by r4j4h** [comment] 2019-03-21 17:25
In the meantime since it is picking up some of the exclusions you could try passing the pieces that aren't making it as arguments,

for example `sonar-scanner -Dsonar.projectKey="myproject"`

**Comment by newtmitch** [comment] 2019-05-13 21:34
@FahdW could you outline where you're putting your `sonar-project.properties` file that you expect this to be picked up as part of the test run?

**Comment by newtmitch** [comment] 2019-05-13 22:08
@FahdW did you see my note in the README about overriding the `sonar-runner.properties` file with your own so you can specify your own properties as needed?

```
docker run -ti \
  -v $(pwd):/root/src \
  -v $(pwd)/sonar-runner.properties:/root/sonar-scanner/conf/sonar-scanner.properties \
  --link sonarqube newtmitch/sonar-scanner sonar-scanner
```

**Comment by newtmitch** [comment] 2019-05-13 22:36
@FahdW I just confirmed this is working fine on my side with the 3.3.0 scanner. I'm going to close this for now until I can reproduce, or when I get more information about the core issue.

**Closed by newtmitch** 2019-05-13 22:36 UTC
Labels: waiting-for-feedback
